[package]
name = "fltk-test"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
error-iter = "0.4.1"
fltk = { version = "1.5.22", features = ["rwh06", "no-pango"] }
log = "0.4.28"
pixels = "0.15.0"
